/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.usmanshahid.jflapcli;

import edu.duke.cs.jflap.gui.Main;

public class App {
    public static void main(String[] args) {
        Main.main(args, false);
    }
}
